name: Cleanup Preview Environment

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    name: Cleanup Preview
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Generate preview name
        id: preview_name
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PREVIEW_NAME="${{ secrets.CLOUD_RUN_SERVICE_NAME }}-pr-${PR_NUMBER}"
          echo "preview_name=${PREVIEW_NAME}" >> $GITHUB_OUTPUT

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_WORKLOAD_IDENTITY_POOL_ID }}/providers/${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_ID }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'
          token_format: 'access_token'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Delete preview service
        run: |
          gcloud run services delete ${{ steps.preview_name.outputs.preview_name }} \
            --region ${{ secrets.CLOUD_RUN_REGION }} \
            --platform managed \
            --quiet || true 